// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/desafios" | "/desafios/[id]/editar" | "/desafios/nuevo" | "/entregas" | "/entregas/[id]" | "/entregas/[id]/editar" | "/entregas/nuevo" | "/equipos" | "/equipos/[id]" | "/equipos/nuevo" | "/evaluaciones" | "/evaluaciones/[id]/editar" | "/evaluaciones/nueva" | "/jueces" | "/jueces/nuevo" | "/login" | "/mentores" | "/mentores/nuevo"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/dashboard": {}
  "/desafios": {}
  "/desafios/[id]/editar": { "id": string; }
  "/desafios/nuevo": {}
  "/entregas": {}
  "/entregas/[id]": { "id": string; }
  "/entregas/[id]/editar": { "id": string; }
  "/entregas/nuevo": {}
  "/equipos": {}
  "/equipos/[id]": { "id": string; }
  "/equipos/nuevo": {}
  "/evaluaciones": {}
  "/evaluaciones/[id]/editar": { "id": string; }
  "/evaluaciones/nueva": {}
  "/jueces": {}
  "/jueces/nuevo": {}
  "/login": {}
  "/mentores": {}
  "/mentores/nuevo": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
