// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../src/app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/desafios/[id]/editar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/desafios/[id]/editar">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/desafios/[id]/editar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/desafios/nuevo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/desafios/nuevo">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/desafios/nuevo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/desafios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/desafios">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/desafios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/entregas/[id]/editar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/entregas/[id]/editar">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/entregas/[id]/editar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/entregas/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/entregas/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/entregas/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/entregas/nuevo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/entregas/nuevo">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/entregas/nuevo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/entregas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/entregas">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/entregas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/equipos/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/equipos/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/equipos/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/equipos/nuevo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/equipos/nuevo">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/equipos/nuevo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/equipos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/equipos">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/equipos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/evaluaciones/[id]/editar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/evaluaciones/[id]/editar">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/evaluaciones/[id]/editar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/evaluaciones/nueva/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/evaluaciones/nueva">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/evaluaciones/nueva/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/evaluaciones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/evaluaciones">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/evaluaciones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/jueces/nuevo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jueces/nuevo">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/jueces/nuevo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/jueces/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jueces">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/jueces/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/mentores/nuevo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mentores/nuevo">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/mentores/nuevo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/mentores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mentores">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/mentores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../src/app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
